openapi: '3.0.2'
info:
  title: On Demand Logs
  version: '1.0'
servers:
  - url: https://localhost:3000/
paths:
  /logs/{filename}:
    get:
      summary: Get 
      parameters:
        - in: path
          name: filename
          schema:
            type: string
          required: true
        - in: query
          name: count
          schema:
            type: integer
          required: false
          description: Number of events to return
        - in: query
          name: filter
          schema:
            type: string
          required: false
          description: Regular expression pattern to get matched events for
      responses:
        '200':
          description: A list of events ordered newest to oldest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfEvents'
        '400':
          description: Could not process request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ArrayOfEvents:
      type: array
      items:
        type: object
        properties:
          raw:
            type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string